### ISSUE TITLE
How to use bibtex instead of biblatex?

### ISSUE THREAD

**Issue by Jzjerry** [Tonanguyxiro/HKUST-GZ_RBM_Research_Proposal#4]
The default ieee style of biblatex seems weird to me, I tried to use **\bibliographystyle{IEEEtran}** but it doesn't work (error due to the mix uses of bibtex and biblatex), then I tried to remove **\usepackage{biblatex}**, but the pdf can't be produced.
 
Should I modify the style file or any other ways to make it work?

**Comment by Tonanguyxiro** [comment]
Hi
I have been trying to solve the problem of reference for a long time but currently it is the only configuration that works, due to the limit of time I am not able to find a proper solution for it currently.

**Comment by Jzjerry** [comment]
I think it's working now, thanks!

**Comment by Jzjerry** [comment]
> I think it's working now, thanks!

Wait, there are still something wrong. My references are missing numbers, but I will try to fix it myself.
